experiment:
    evoluation_goal: a.npy
    max_generation: 100

tensor_network:
    initializer: tf.compat.v1.random_normal_initializer
    initializer_params:
        mean: 0.0
        stddev: 1.0

optimization:
    evaluate_repeat: 5
    max_iterations: 50000
    optimizer: tf.compat.v1.train.AdamOptimizer
    optimizer_params:
        learning_rate: 0.001

agent_behavier:
    timeout: 1800
    allow_fewer_repeat_after_timeout: True

generation_property:
    n_individuals_span: 200
    n_individuals_survive: 100
