experiment:
    evoluation_goal: a.npy
    max_generation: 30
    random_init: True

tensor_network:
    initializer: tensorflow.compat.v1.random_normal_initializer
    initializer_params:
        mean: 0.0
        stddev: 1.0

optimization:
    max_iterations: 50000
    optimizer: tensorflow.compat.v1.train.AdamOptimizer
    optimizer_params:
        learning_rate: 0.001

agent_behavier:
    n_iter: 10
    estimation_iter: 100
    timeout: 1800
    # if we can finish % of the iterations before timeout, then we will go on
    allow_waiting_after_timeout_rate: 0.5
    max_abnormal_before_block: 10

generation_property:
    evaluate_repeat: 2
    # this allows job to be repeated even a hard timeout is reported
    still_allow_repeat_after_hard_timeout: True
    society_property:
        n_societies: 2
        society:
            # define property of each society
            - n_individuals_span: 200
              fitness_func: FITNESS_FUNCS.defualt
              evolution:
                - ops: EVOLVE_OPS.elimination
                  n_individuals_survive: 100 
                - ops: EVOLVE_OPS.mutation
                  prob: 0.05
                - ops: EVOLVE_OPS.fillup
                  adj_func: Individual.naive_random_adj_matrix_with_sparsity_limitation

            - n_individuals_span: 200
              fitness_func: FITNESS_FUNCS.defualt
              evolution:
                - ops: EVOLVE_OPS.elimination
                  n_individuals_survive: 100 
                - ops: EVOLVE_OPS.mutation
                  prob: 0.05
                - ops: EVOLVE_OPS.fillup
                  adj_func: Individual.naive_random_adj_matrix_with_sparsity_limitation

individual_property:
    discard_hard_timeout_result: False
    random_initilization_property:
        tn_size: 4
        tn_rank: 2
        presented_shape: 2
        init_sparsity: -0.00001

evolution_property:
    elimiation_threshold: 0.8
    immigration_prob: 0
    immigration_number: 5
    crossover_alpha: 1
    mutation_prob: 0.05

overlord_propert:
    tik: 1